<a href="https://colab.research.google.com/github/ganesh5124/AI-Assited-Devops/blob/main/Welcome_to_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
s = pd.Series([1,2,3,4,5,6])
s

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [ ]:
s.name = "calories"
s

0    1
1    2
2    3
3    4
4    5
5    6
Name: calories, dtype: int64

In [ ]:
s.dtype

dtype('int64')

In [ ]:
s.values

array([1, 2, 3, 4, 5, 6])

In [ ]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [ ]:
# iloc ==> number based indexing

s.iloc[[1,3]]

1    2
3    4
Name: calories, dtype: int64

In [ ]:
index = ['apple', 'banana','mango','grape', 'pappay', 'strawberry']

In [ ]:
s.index = index
s

apple         1
banana        2
mango         3
grape         4
pappay        5
strawberry    6
Name: calories, dtype: int64

In [ ]:
s['apple']

np.int64(1)

In [ ]:
# loc ==> label based indexing
s.loc['apple']

np.int64(1)

In [ ]:
#  In label based Indexing your start as well as stop value both are included in the output
s['apple': 'mango']

apple     1
banana    2
mango     3
Name: calories, dtype: int64

In [ ]:
# prompt: create dictitory type data of fruits and its calories in 10 entries 0.0 type values

fruits_calories = {
    'apple': 52.0,
    'banana': 89.0,
    'orange': 47.0,
    'grape': 69.0,
    'strawberry': 33.0,
    'blueberry': 57.0,
    'watermelon': 30.0,
    'pineapple': 50.0,
    'mango': 60.0,
    'kiwi': 61.0,
}

fruits_calories

{'apple': 52.0,
 'banana': 89.0,
 'orange': 47.0,
 'grape': 69.0,
 'strawberry': 33.0,
 'blueberry': 57.0,
 'watermelon': 30.0,
 'pineapple': 50.0,
 'mango': 60.0,
 'kiwi': 34}

In [ ]:
# Conditional Selection
fruit_calories = pd.Series(fruits_calories, name = "Protein")
fruit_calories

apple         52.0
banana        89.0
orange        47.0
grape         69.0
strawberry    33.0
blueberry     57.0
watermelon    30.0
pineapple     50.0
mango         60.0
kiwi          34.0
Name: Protein, dtype: float64

In [ ]:
# logical operators
fruit_calories[(fruit_calories>40) | (fruit_calories<50)]

apple         52.0
banana        89.0
orange        47.0
grape         69.0
strawberry    33.0
blueberry     57.0
watermelon    30.0
pineapple     50.0
mango         60.0
kiwi          34.0
Name: Protein, dtype: float64

In [ ]:
# Modifying the series
fruit_calories['apple'] = 100
fruit_calories

apple         100.0
banana         89.0
orange         47.0
grape          69.0
strawberry     33.0
blueberry      57.0
watermelon     30.0
pineapple      50.0
mango          60.0
kiwi           34.0
Name: Protein, dtype: float64

In [ ]:
# prompt: # Lets start DataFrames
# # give me some dummy data for dataframe( name, aage, department and salary)

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 28, 32],
    'Department': ['Sales', 'Marketing', 'Engineering', 'Sales', 'HR'],
    'Salary': [50000, 60000, 80000, 55000, 65000]
}

df = pd.DataFrame(data)
df

      Name  Age   Department  Salary
0    Alice   25        Sales   50000
1      Bob   30    Marketing   60000
2  Charlie   35  Engineering   80000
3    David   28        Sales   55000
4      Eve   32           HR   65000

In [ ]:
df.tail(4)

      Name  Age   Department  Salary
1      Bob   30    Marketing   60000
2  Charlie   35  Engineering   80000
3    David   28        Sales   55000
4      Eve   32           HR   65000

In [ ]:
df.loc[2:3, ['Name', 'Age'], ]

      Name  Age
2  Charlie   35
3    David   28

In [ ]:
df.iloc[2:3]

      Name  Age   Department  Salary
2  Charlie   35  Engineering   80000

In [ ]:
df[['Age', 'Salary']]

   Age  Salary
0   25   50000
1   30   60000
2   35   80000
3   28   55000
4   32   65000

In [ ]:
df

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   80000
3    David   28   55000
4      Eve   32   65000

In [ ]:
df.drop('Age', axis=1, inplace=True)

KeyError: "['Age'] not found in axis"

In [ ]:
df.shape

(5, 3)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Department  5 non-null      object
 2   Salary      5 non-null      int64
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [ ]:
df

      Name   Department  Salary
0    Alice        Sales   50000
1      Bob    Marketing   60000
2  Charlie  Engineering   80000
3    David        Sales   55000
4      Eve           HR   65000